### ISSUE TITLE
Switching focus automatically

### ISSUE THREAD

**Issue by agzam** [alpha22jp/atomic-chrome#6] opened 2016-10-31 17:32 UTC
Would be nice if it changes focus to Emacs frame and back to Chrome on `C-c C-c`

**Comment by alpha22jp** [comment] 2016-11-01 14:21
Hi @agzam 

I agree your idea. But window focus is controlled by OS. There is no way to handle it by Emacs Lisp.

**Comment by agzam** [comment] 2016-11-01 14:31
I understand. I'm in the phone, can't check right now. is there a hook for C-c C-c? "Edit with Emacs" provides one.

**Comment by agzam** [comment] 2016-11-02 02:25
I see that there's already `atomic-chrome-edit-mode-hook` which OS X users for example can use to switch focus on Emacs app by running something like `shell-command "open -a \"Emacs\""`

but there's no hook for `C-c C-c`. Can you add it? Thanks!

**Comment by alpha22jp** [comment] 2016-11-02 13:05
Hi @agzam 

> but there's no hook for C-c C-c. Can you add it?

I added the hook `atomic-chrome-edit-done-hook` at 7145210. Please use it.

> However the latter does open new Emacs frame and focuses on it.

I took a quick look at Edit with Emacs. It uses `raise-frame` and `select-frame-set-input-focus` when it creates the buffer for editing. They appear to tell OS to set focus on the window.

As for closing, Edit with Emacs doesn't do anything special. So the focus change would be a natural behaviour caused by closing the window for editing. Actually, the focus does not return to Chrome when I set `edit-server-new-frame` to nil.

Anyway, I'll try to implement the same way Edit with Emacs does and see how it works. Please give me some time.

**Comment by agzam** [comment] 2016-11-02 17:38
>  added the hook atomic-chrome-edit-done-hook

You are awesome! Thanks a lot! This is very inlined with "Emacs Tao" - *don't do anything special, provide necessary hooks and customizations and let the user do whatever her heart desires*. 

This package now is one of my favorites. I tended not to use "Edit with Emacs" too much because workflow felt a bit "clunky". This feels much cleaner.

**Closed** 2016-11-02 17:57 UTC

**Comment by alpha22jp** [comment] 2016-11-03 07:13
Hi @agzam

I just commited some modifications for window focus issue. For my environment (Ubuntu 14.04 and Windows 7), the window focus works in the same way as Edit with Emacs. Please check it.
